version: '3.3'


services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

    devices:
      - "/dev/bus/usb/001/002:/dev/bus/usb/001/002"
    privileged: true

#    extra_hosts:
#      - "host.docker.internal:host-gateway"

